// ── {{AGENT_DISPLAY_NAME}} — {{COMPANY_NAME}} {{AGENT_ROLE}} ──────
// Generated by The Forge deploy-all.mjs
// Company: {{COMPANY_NAME}} ({{COMPANY_SLUG}})
// Agent: {{AGENT_DISPLAY_NAME}} ({{AGENT_SLUG}})

import { randomUUID } from "node:crypto";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

// ── Deploy-time Constants ───────────────────────────

const AGENT_NAME = "{{AGENT_NAME}}";
const AGENT_SLUG = "{{AGENT_SLUG}}";
const AGENT_DISPLAY_NAME = "{{AGENT_DISPLAY_NAME}}";
const AGENT_ROLE = "{{AGENT_ROLE}}";
const COMPANY_NAME = "{{COMPANY_NAME}}";
const COMPANY_SLUG = "{{COMPANY_SLUG}}";
const COMPANY_WEBSITE = "{{COMPANY_WEBSITE}}";

// These are filled at deploy time from company config
const CRON_CONFIG = {{CRON_CONFIG}};
const ALERT_ROUTING = {{ALERT_ROUTING}};
const CHANNELS = {{CHANNELS}};
const SLASH_COMMANDS = {{SLASH_COMMANDS}};

// ── Runtime Config (from env / plist) ───────────────

const XAPP = process.env.SLACK_XAPP_TOKEN || "{{SLACK_XAPP_TOKEN}}";
const XOXB = process.env.SLACK_XOXB_TOKEN || "{{SLACK_XOXB_TOKEN}}";
const BOT_USER_ID = process.env.SLACK_BOT_USER_ID || "{{SLACK_BOT_USER_ID}}";
const DEEPSEEK_KEY = process.env.DEEPSEEK_API_KEY || "{{DEEPSEEK_API_KEY}}";
const DEEPSEEK_URL = "https://api.deepseek.com/v1/chat/completions";
const SLACK_API = "https://slack.com/api";
const NOTION_KEY = process.env.NOTION_API_KEY || "{{NOTION_API_KEY}}";
const NOTION_VERSION = "2022-06-28";
const NOTION_DATABASES = (() => { try { return JSON.parse(process.env.NOTION_DATABASES || ""); } catch { return {}; } })();
const OBSIDIAN_VAULT = process.env.OBSIDIAN_VAULT || "{{OBSIDIAN_VAULT}}";
const KNOWLEDGE_FILES = (process.env.KNOWLEDGE_FILES || "{{KNOWLEDGE_FILES}}").split(",").filter(Boolean);

// ── Import Utilities ────────────────────────────────

let utils;
try {
  utils = await import("./listener-utils.mjs");
} catch {
  utils = await import("{{AGENT_HUB_UTILS}}");
}

const { spawnSubAgent, spawnSubAgents, routeAlert, formatAlert, notifyOwner, logCron, healthCheck } = utils;

// ── Deduplication ───────────────────────────────────

const recentEvents = new Set();
function isDuplicate(channel, user, ts) {
  const key = `${channel}:${user}:${ts}`;
  if (recentEvents.has(key)) return true;
  recentEvents.add(key);
  setTimeout(() => recentEvents.delete(key), 5000);
  return false;
}

// ── Active Conversations (30-sec DM window, 30-min thread window) ─

const activeThreads = new Map();
const activeDms = new Map(); // channel -> timestamp, for DM no-@mention window

function trackThread(threadTs) {
  if (!threadTs) return;
  activeThreads.set(threadTs, Date.now());
  setTimeout(() => {
    const last = activeThreads.get(threadTs);
    if (last && Date.now() - last >= 30 * 60 * 1000) activeThreads.delete(threadTs);
  }, 30 * 60 * 1000);
}

function trackDm(channel) {
  activeDms.set(channel, Date.now());
  setTimeout(() => {
    const last = activeDms.get(channel);
    if (last && Date.now() - last >= 30 * 1000) activeDms.delete(channel);
  }, 30 * 1000);
}

function isActiveThread(event) {
  const threadTs = event.thread_ts || event.ts;
  if (activeThreads.has(threadTs)) {
    activeThreads.set(threadTs, Date.now());
    return true;
  }
  for (const [key] of activeThreads) {
    if (threadTs.startsWith(key) || key.startsWith(threadTs)) {
      activeThreads.set(key, Date.now());
      return true;
    }
  }
  return false;
}

function isActiveDm(channel) {
  if (activeDms.has(channel)) {
    activeDms.set(channel, Date.now());
    return true;
  }
  return false;
}

// ── Slack API ───────────────────────────────────────

async function slackApi(method, body, token = XOXB) {
  const res = await fetch(`${SLACK_API}/${method}`, {
    method: "POST",
    headers: { "Authorization": `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  return res.json();
}

async function getWebSocketUrl() {
  const res = await slackApi("apps.connections.open", {}, XAPP);
  if (!res.ok) throw new Error(`apps.connections.open failed: ${res.error}`);
  return res.url;
}

// Update AGENT_IDS with all agent bot user IDs for inter-agent awareness
const AGENT_IDS = "{{AGENT_IDS}}".split(",").filter(Boolean);

function isMentioned(text) {
  if (text.includes(`<@${BOT_USER_ID}>`)) return true;
  for (const id of AGENT_IDS) {
    if (id && id !== BOT_USER_ID && text.includes(`<@${id}>`)) return true;
  }
  return false;
}

function cleanText(text) {
  return text.replace(new RegExp(`<@${BOT_USER_ID}>\\s*`, "g"), "").trim();
}

// ── Notion API ──────────────────────────────────────

async function notion(method, path, body = null) {
  if (!NOTION_KEY) return { error: "No Notion API key" };
  const opts = {
    method,
    headers: { "Authorization": `Bearer ${NOTION_KEY}`, "Notion-Version": NOTION_VERSION, "Content-Type": "application/json" },
  };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(`https://api.notion.com/v1${path}`, opts);
  return res.json();
}

async function notionSearch(query) {
  return notion("POST", "/search", { query, page_size: 10 });
}

async function notionQueryDB(dbId, filter = {}, pageSize = 20) {
  return notion("POST", `/databases/${dbId}/query`, {
    page_size: pageSize,
    sorts: [{ timestamp: "last_edited_time", direction: "descending" }],
    ...(Object.keys(filter).length ? { filter } : {}),
  });
}

// ── Obsidian Knowledge ──────────────────────────────

let loadedKnowledge = "";

function loadKnowledge() {
  if (!OBSIDIAN_VAULT) return "";
  const parts = [];
  for (const file of KNOWLEDGE_FILES) {
    const path = join(OBSIDIAN_VAULT, file);
    if (existsSync(path)) {
      try {
        const content = readFileSync(path, "utf-8");
        parts.push(`### ${file.replace(".md", "")}\n${content.substring(0, 1500)}`);
        console.log(`[${AGENT_NAME}] Loaded knowledge: ${file}`);
      } catch (e) {
        console.error(`[${AGENT_NAME}] Failed to read ${file}:`, e.message);
      }
    }
  }
  loadedKnowledge = parts.join("\n\n---\n\n");
  return loadedKnowledge;
}

// ── System Prompt ───────────────────────────────────

const BASE_SYSTEM_PROMPT = `You are {{AGENT_DISPLAY_NAME}}, the {{COMPANY_NAME}} {{AGENT_ROLE}} agent.

## Identity
- {{COMPANY_NAME}} is a {{COMPANY_DESCRIPTION}}.
- Website: {{COMPANY_WEBSITE}}
- You manage {{DOMAIN_SCOPE}}.

## What You Do
{{AGENT_RESPONSIBILITIES}}

## What You DO NOT Do
{{AGENT_BOUNDARIES}}

## Agent Coordination
{{AGENT_COORDINATION}}

## Cron Jobs You Run
{{AGENT_CRON_JOBS}}

## Channels
- Critical: ${CHANNELS.critical || "#critical"}
- Alerts: ${CHANNELS.alerts || "#alerts"}
- General: ${CHANNELS.general || "#general"}

## Response Style
{{AGENT_PERSONALITY}}`;

function buildSystemPrompt() {
  const now = new Date().toLocaleString("en-US", { timeZone: "America/New_York", weekday: "long", year: "numeric", month: "long", day: "numeric", hour: "numeric", minute: "2-digit", timeZoneName: "short" });
  return `${BASE_SYSTEM_PROMPT}

## Current Date & Time
It is now **${now}**. Use this for all date calculations. Do NOT guess the date.

## Obsidian Knowledge (live from vault)
${loadedKnowledge || "(no knowledge loaded)"}`;
}

const FALLBACK_REPLY = (name) => `Hey ${name}! I'm ${AGENT_DISPLAY_NAME}, ${AGENT_ROLE} for ${COMPANY_NAME}. How can I help?`;

// ── LLM ────────────────────────────────────────────

async function think(messages) {
  if (!DEEPSEEK_KEY) return null;
  try {
    const res = await fetch(DEEPSEEK_URL, {
      method: "POST",
      headers: { "Authorization": `Bearer ${DEEPSEEK_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model: "deepseek-chat", messages, temperature: 0.7, max_tokens: 1500 }),
    });
    const j = await res.json();
    if (j.error) { console.error(`[${AGENT_NAME}] LLM error:`, JSON.stringify(j.error)); return null; }
    return j.choices?.[0]?.message?.content || null;
  } catch (e) {
    console.error(`[${AGENT_NAME}] LLM error:`, e.message);
    return null;
  }
}

// ── Context Fetch ───────────────────────────────────

async function fetchContext(channel, thread, count = 10) {
  try {
    const params = { channel, limit: count };
    if (thread) params.ts = thread;
    const res = await slackApi("conversations.replies", params);
    if (!res.ok || !res.messages) return [];
    return res.messages
      .filter((m) => m.text)
      .map((m) => {
        let text = m.text;
        text = text.replace(/<@\w+>/g, (match) => {
          const id = match.slice(2, -1);
          return id === BOT_USER_ID ? `@${AGENT_NAME}` : match;
        });
        text = text.replace(/<!channel>/g, "@channel");
        text = text.replace(/<([^>|]+)\|[^>]+>/g, "$1");
        text = text.replace(/<([^>]+)>/g, "$1");
        return { role: m.user === BOT_USER_ID ? "assistant" : "user", content: text };
      });
  } catch {
    return [];
  }
}

// ── Context Folding ─────────────────────────────────

async function foldContext(messages) {
  const estimateTokens = (arr) => arr.reduce((sum, m) => sum + Math.ceil((m.content?.length || 0) / 4), 0);
  if (estimateTokens(messages) < 8000) return messages;
  const split = Math.floor(messages.length * 0.6);
  if (split < 4) return messages;
  const toSummarize = messages.slice(0, split);
  const recent = messages.slice(split);
  try {
    const summary = await think([
      { role: "system", content: "Summarize this conversation in 2-3 sentences. Preserve: names, details, decisions, action items." },
      { role: "user", content: toSummarize.map(m => `[${m.role}]: ${m.content}`).join("\n") },
    ]);
    if (summary) {
      console.log(`[${AGENT_NAME}] Context folded: ${toSummarize.length} msgs → summary`);
      return [{ role: "system", content: `[Earlier conversation: ${summary}]` }, ...recent];
    }
  } catch (e) {
    console.error(`[${AGENT_NAME}] Context fold failed:`, e.message);
  }
  return messages;
}

// ── Sub-Agent Spawning (integrated) ─────────────────

/**
 * Run a cron job that spawns sub-agents for parallel research.
 */
async function runResearchCron(topic, queries) {
  const tasks = queries.map((q, i) => ({
    role: `${topic} Agent ${String.fromCharCode(65 + i)}`,
    prompt: q,
  }));
  
  return spawnSubAgents(tasks, {
    apiKey: DEEPSEEK_KEY,
    maxTokens: 2000,
  });
}

// ── Alert Posting ───────────────────────────────────

async function postAlert(severity, message, source = "") {
  const route = routeAlert(severity, ALERT_ROUTING, CHANNELS);
  const text = formatAlert(severity, message, source);
  
  try {
    // Try to resolve channel name to ID via Slack API
    const chList = await slackApi("conversations.list", { types: "public_channel,private_channel", limit: 200 });
    const channel = (chList.channels || []).find(c => `#${c.name}` === route.channel || c.name === route.channel.replace("#", ""));
    const channelId = channel?.id || route.channel;
    
    await slackApi("chat.postMessage", {
      channel: channelId,
      text,
      unfurl_links: false,
      unfurl_media: false,
    });
    console.log(`[${AGENT_NAME}] Alert posted to ${route.channel}: [${route.label}] ${message.substring(0, 80)}`);
    return true;
  } catch (e) {
    console.error(`[${AGENT_NAME}] Alert failed:`, e.message);
    return false;
  }
}

// ── Handle ──────────────────────────────────────────

async function handle(channel, user, text, thread) {
  try {
    let userName = "";
    try {
      const timeout = new Promise((_, r) => setTimeout(() => r(new Error("timeout")), 5000));
      const u = await Promise.race([slackApi("users.info", { user }), timeout]);
      if (u?.ok && u.user?.real_name) userName = u.user.real_name;
    } catch (e) {
      // users.info failed — proceed without name
    }
    const displayName = userName || "someone";

    console.log(`[${AGENT_NAME}] Handling "${text.substring(0, 60)}" from ${displayName}`);

    // Check for sub-agent spawn request
    if (text.toLowerCase().includes("spawn") && (text.toLowerCase().includes("agent") || text.toLowerCase().includes("research"))) {
      await slackApi("chat.postMessage", {
        channel,
        text: `🔄 Spawning sub-agents for that task. I'll report back when they're done.`,
        unfurl_links: false,
        unfurl_media: false,
      });
      
      // Delegate to sub-agents
      const result = await spawnSubAgent(
        `The user ${displayName} asked: "${text}". Execute this task thoroughly. Return specific, actionable results.`,
        { role: `${AGENT_DISPLAY_NAME} Sub-Agent`, apiKey: DEEPSEEK_KEY, maxTokens: 2500 }
      );
      
      await slackApi("chat.postMessage", {
        channel,
        text: result.text,
        thread_ts: thread,
        unfurl_links: false,
        unfurl_media: false,
      });
      trackThread(thread);
      return;
    }

    const history = await fetchContext(channel, thread);
    const prior = history.filter(m => m.content && m.content.trim()).slice(0, -1);
    const messages = [
      { role: "system", content: buildSystemPrompt() },
      ...prior,
      { role: "user", content: `[${displayName}]: ${text}` },
    ];

    const folded = await foldContext(messages);
    const llmReply = await think(folded);

    let reply;
    if (llmReply) {
      reply = llmReply;
    } else {
      reply = FALLBACK_REPLY(displayName.split(" ")[0]);
    }

    await slackApi("chat.postMessage", { channel, text: reply, thread_ts: thread, unfurl_links: false, unfurl_media: false });
    trackThread(thread);
    console.log(`[${AGENT_NAME}] Replied in ${channel}`);
  } catch (e) {
    console.error(`[${AGENT_NAME}] handle error:`, e.message);
    try {
      await slackApi("chat.postMessage", { channel, text: "Sorry, something went wrong. Try again?", unfurl_links: false, unfurl_media: false });
      trackThread(thread);
    } catch {}
  }
}

// ── Slash Commands ──────────────────────────────────

async function handleCommand(command, channel, user, text, triggerId) {
  console.log(`[${AGENT_NAME}] COMMAND ${command} from ${user}: "${text}"`);

  let responseText = `Command \`${command}\` received.`;

  try {
    switch (command) {
      default: {
        // Generic handler: send to LLM
        const messages = [
          { role: "system", content: buildSystemPrompt() },
          { role: "user", content: `User invoked ${command}${text ? ` with: "${text}"` : ""}. Respond helpfully and concisely.` },
        ];
        const llmReply = await think(messages);
        if (llmReply) responseText = llmReply;
        break;
      }
    }
  } catch (e) {
    console.error(`[${AGENT_NAME}] Command error:`, e.message);
    responseText = `Sorry, command \`${command}\` failed: ${e.message}`;
  }

  await slackApi("chat.postMessage", {
    channel,
    text: responseText,
    unfurl_links: false,
    unfurl_media: false,
  });
}

// ── Cron Engine ─────────────────────────────────────

/**
 * Execute a single cron job.
 */
async function executeCronJob(job) {
  logCron(job.job, "started", job.description);
  
  try {
    let result;
    
    switch (job.job) {
      case "health_check": {
        const health = await healthCheck({ slackApi, agentName: AGENT_NAME, botUserId: BOT_USER_ID });
        if (!health.healthy) {
          const failures = Object.entries(health.checks)
            .filter(([, c]) => c.status !== "ok")
            .map(([name, c]) => `  ${name}: ${c.detail}`)
            .join("\n");
          await postAlert("p1", `Health check FAILED:\n${failures}`, AGENT_NAME);
        } else {
          console.log(`[${AGENT_NAME}] Health check: all OK`);
        }
        result = health;
        break;
      }
      
      case "morning_standup":
      case "morning_sweep":
      case "stale_sweep":
      case "midday_check":
      case "eod_summary":
      case "weekly_review":
      case "revenue_report":
      default: {
        // LLM-powered cron: ask the agent to produce the report
        const cronPrompt = [
          { role: "system", content: buildSystemPrompt() },
          {
            role: "user",
            content: `CRON JOB: ${job.job} (${job.description}). Execute this scheduled task now. Return a concise report or take the appropriate action. If posting to a channel, tell me the channel name and message.`,
          },
        ];
        result = await think(cronPrompt);
        
        if (result && job.channel) {
          // Post to the designated channel
          const chName = CHANNELS[job.channel] || job.channel;
          const chList = await slackApi("conversations.list", { types: "public_channel,private_channel", limit: 200 });
          const ch = (chList.channels || []).find(c => `#${c.name}` === `#${chName}` || c.name === chName);
          const channelId = ch?.id || chName;
          
          await slackApi("chat.postMessage", {
            channel: channelId,
            text: result,
            unfurl_links: false,
            unfurl_media: false,
          });
          console.log(`[${AGENT_NAME}] Cron "${job.job}" posted to #${chName}`);
        }
        break;
      }
    }
    
    logCron(job.job, "completed");
    return result;
  } catch (e) {
    logCron(job.job, "failed", e.message);
    return null;
  }
}

/**
 * Start the cron job scheduler. Uses setTimeout-based scheduling
 * (no dependency on node-cron — works in Node 22+ stdlib).
 */
function startCron() {
  if (!CRON_CONFIG || !CRON_CONFIG.length) {
    console.log(`[${AGENT_NAME}] No cron jobs configured`);
    return;
  }

  console.log(`[${AGENT_NAME}] Scheduling ${CRON_CONFIG.length} cron jobs:`);
  
  const scheduled = new Set();
  
  function scheduleNext(job) {
    if (scheduled.has(job.job)) return;
    scheduled.add(job.job);
    
    // Parse cron expression and schedule
    const ms = nextCronTime(job.schedule);
    const label = `[${AGENT_NAME}] Cron "${job.job}" → ${new Date(Date.now() + ms).toLocaleString()}`;
    console.log(label);
    
    setTimeout(async () => {
      await executeCronJob(job);
      scheduleNext(job); // Re-schedule
    }, ms);
  }
  
  for (const job of CRON_CONFIG) {
    scheduleNext(job);
  }
}

/**
 * Parse a 5-field cron expression and return ms until next trigger.
 * Supports: minute hour day-of-month month day-of-week
 * Also supports interval notation like "0 asterisk-slash-6 asterisk asterisk asterisk asterisk" for every 6 hours.
 */
function nextCronTime(expr) {
  const parts = expr.trim().split(/\s+/);
  if (parts.length < 5) return 3600000; // default: 1 hour
  
  const now = new Date();
  const [minField, hourField, domField, monthField, dowField] = parts;
  
  // Simple interval parsing: star-slash-N means every N units
  const parseField = (field, current, max) => {
    if (field === "*") return null; // every unit
    if (field.startsWith("*/")) {
      const interval = parseInt(field.slice(2));
      const next = current + interval;
      return next >= max ? null : next; // null = roll over
    }
    const val = parseInt(field);
    return isNaN(val) ? null : val;
  };
  
  const targetMin = parseField(minField, now.getMinutes(), 60);
  const targetHour = parseField(hourField, now.getHours(), 24);
  
  let next = new Date(now);
  next.setSeconds(0);
  next.setMilliseconds(0);
  
  if (targetMin !== null && targetHour !== null) {
    next.setHours(targetHour, targetMin);
  } else if (targetMin !== null) {
    next.setMinutes(targetMin);
    if (targetMin <= now.getMinutes()) next.setHours(next.getHours() + 1);
  } else if (targetHour !== null) {
    next.setHours(targetHour, 0);
    if (targetHour <= now.getHours()) next.setDate(next.getDate() + 1);
  } else {
    // Both wildcards or interval — run hourly
    if (minField.startsWith("*/")) {
      const interval = parseInt(minField.slice(2));
      next.setMinutes(Math.ceil(now.getMinutes() / interval) * interval);
    } else {
      next.setMinutes(next.getMinutes() + 1);
    }
  }
  
  let diff = next.getTime() - now.getTime();
  
  // If interval-based and the next time is too far, adjust
  if (minField.startsWith("*/")) {
    const interval = parseInt(minField.slice(2));
    if (diff > interval * 60 * 1000) diff = interval * 60 * 1000;
  }
  
  return Math.max(1000, diff); // Minimum 1 second
}

// ── Socket Mode ─────────────────────────────────────

async function connect() {
  const url = await getWebSocketUrl();
  console.log(`[${AGENT_NAME}] Connecting to Slack Socket Mode...`);
  const ws = new WebSocket(url);
  let pingInterval;

  ws.onopen = () => {
    console.log(`[${AGENT_NAME}] Connected. Listening.`);
    pingInterval = setInterval(() => {
      try { ws.send(JSON.stringify({ type: "ping" })); } catch {}
    }, 30000);
  };

  ws.onmessage = async (event) => {
    try {
      const msg = JSON.parse(event.data);
      console.log(`[${AGENT_NAME}] recv type=${msg.type}`);

      if (msg.type === "hello") {
        console.log(`[${AGENT_NAME}] Hello, connections: ${msg.num_connections}`);
        return;
      }

      if (msg.type === "disconnect") {
        console.log(`[${AGENT_NAME}] Disconnect: ${msg.reason}. Reconnecting...`);
        clearInterval(pingInterval);
        ws.close();
        setTimeout(connect, 1000);
        return;
      }

      if (msg.type === "events_api" && msg.payload?.event) {
        const evt = msg.payload.event;
        ws.send(JSON.stringify({ envelope_id: msg.envelope_id, type: "ack" }));

        if (evt.user === BOT_USER_ID) return;
        if (evt.subtype === "message_changed" || evt.subtype === "message_deleted") return;

        const text = evt.text || "";

        // Thread continuation (30-min window, no @mention needed)
        if (evt.type === "message" && isActiveThread(evt) && text.trim()) {
          await handle(evt.channel, evt.user, cleanText(text), evt.ts);
          return;
        }

        // app_mention event
        if (evt.type === "app_mention") {
          if (isDuplicate(evt.channel, evt.user, evt.ts)) return;
          await handle(evt.channel, evt.user, cleanText(text), evt.ts);
          trackDm(evt.channel); // start DM conversation mode
          return;
        }

        // @mention in regular message
        if (evt.type === "message" && isMentioned(text)) {
          if (isDuplicate(evt.channel, evt.user, evt.ts)) return;
          await handle(evt.channel, evt.user, cleanText(text), evt.ts);
          trackDm(evt.channel); // start DM conversation mode
          return;
        }
      }
    } catch (e) {
      console.error(`[${AGENT_NAME}] Error:`, e.message);
    }
  };

  ws.onerror = (err) => console.error(`[${AGENT_NAME}] WS error:`, err.message || err);

  ws.onclose = (event) => {
    console.log(`[${AGENT_NAME}] Closed (${event.code}). Reconnect in 5s...`);
    clearInterval(pingInterval);
    setTimeout(connect, 5000);
  };
}

// ── Start ───────────────────────────────────────────

console.log(`[${AGENT_NAME}] Starting ${AGENT_DISPLAY_NAME} — ${COMPANY_NAME} ${AGENT_ROLE}`);
if (OBSIDIAN_VAULT) {
  console.log(`[${AGENT_NAME}] Loading Obsidian knowledge...`);
  loadKnowledge();
}
console.log(`[${AGENT_NAME}] Starting cron engine...`);
startCron();
connect();
